development:
  adapter: mysql
  encoding: utf8
  host: database.local
  user: root
  password: bleh
  database: pro_jobs_development
  pool: 5
  
test: &TEST
  adapter: mysql
  encoding: utf8
  host: database.local
  user: root
  password: bleh
  database: pro_jobs_test
  pool: 5
  
staging:
  adapter: mysql
  encoding: utf8
  database: pro_jobs_staging
  username: root
  password:
  pool: 5
  
production:
  encoding: utf8
  adapter: mysql
  database: pro_jobs_production
  username: root
  password:
  pool: 5

cucumber:
  <<: *TEST
